version: '3'

services:
  dockerdotnetoauth:
    image: dockerdotnetoauth
    build:
      context: ./DockerDotNetOAuth
      dockerfile: Dockerfile

  identityserver:
    image: identityserver
    build:
      context: ./IdentityServer
      dockerfile: Dockerfile
